### ISSUE TITLE
How to add a new grid-stack-item for Angular6 project gives error while adding

### ISSUE THREAD

**Issue by vishal1025** [pfms84/lb-gridstack#1]
If I try to add the GridStackService, it gives error

import { GridstackService } from '@libria/gridstack/services/gridstack.service';

gives error

Module not found: Error: Can't resolve '@libria/gridstack/services/gridstack.service' in 'C:\Users\Admin\lbgridstack\src\app'

How to add a new widget

**Comment by pfms84** [comment]
Sorry for the really late response. 
The GridstackService is used internally by the lib.
This lib must be used only through its components (lb-gridstack and lb-gridstack-item).

**Comment by shadowjustice** [comment]
Hi, I understand gridstackservice is used internally but that still does not explain how to add a new item programmatically. I searched for it but is it correct to say that we can't add widgets dynamically? For now I'm importing jquery and will be trying to add new items tru js function.
